name: IBM Cloud CLI
description: Install and configure the IBM Cloud CLI for working with IBM Cloud
branding:
  icon: upload-cloud
  color: blue
inputs:
  plugins:
    description: |
      A comma, space, or newline separated list of CLI plugins to be installed.
      The plugins can listed as PLUGIN_NAME (e.g. container-service) or PLUGIN_NAME@VERSION (e.g. container-service@0.4.102)
      For more information about plugins see https://cloud.ibm.com/docs/cli?topic=cli-plug-ins
outputs:
  version:
    description: The version of the IBM Cloud CLI that was installed
runs:
  using: node20
  main: dist/index.js
