name: 'IBM Cloud CLI'
description:
  'Install and configure the IBM Cloud CLI for working with IBM Cloud'
branding:
  icon: 'upload-cloud'
  color: 'blue'
inputs:
  IBMCLOUD_API_KEY:
    description: 'Your API key to access IBM Cloud'
    required: false
  IBMCLOUD_REGION:
    description: 'The region to access IBM Cloud'
    required: false
    default: 'us-south'
outputs:
  version:
    description: 'The version of the IBM Cloud CLI that was installed'
runs:
  using: node20
  main: dist/index.js
