name: Test this action
on:
  pull_request:
  push:
  workflow_dispatch:
permissions:
  contents: read
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up ibmcloud CLI
      uses: ./
    - run: ibmcloud --version

  check-dist:
    name: Check dist directory is up to date
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: "20"
        cache: npm
    - run: npm run package
    - run: git diff --exit-code
